version: "3"

services:
  production:
    build:
      context: .
      target: production
    image: ${DOCKERHUB_USERNAME}/todo-app:latest
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "8080:80"
