version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  development:
    build:
      context: .
      target: development
    depends_on:
      - mongo
    env_file:
      - .flaskenv
      - .env.public
    environment:
      MONGO_URI: mongodb://mongo:27017/
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./todo_app:/opt/todo-app/todo_app
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    depends_on:
      - development
    network_mode: "host"
    environment:
      CYPRESS_OAUTH_USERNAME: ${CYPRESS_OAUTH_USERNAME}
      CYPRESS_OAUTH_PASSWORD: ${CYPRESS_OAUTH_PASSWORD}
      CYPRESS_OAUTH_OTP_SECRET: ${CYPRESS_OAUTH_OTP_SECRET}
