version: "3"

services:
  development:
    build:
      context: .
      target: development
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./todo_app:/opt/todo-app/todo_app
