version: "3"

services:
  production:
    build:
      context: .
      target: production
    env_file:
      - .env
    ports:
      - "8080:80"
  development:
    build:
      context: .
      target: development
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./todo_app:/opt/todo-app/todo_app
  test:
    build:
      context: .
      target: test
    env_file:
      - .env.test
  test-e2e:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    depends_on:
      - development
    network_mode: "host"
