version: "3"

services:
  production:
    build:
      context: ..
      target: production
      dockerfile: docker/Dockerfile
    image: ${DOCKERHUB_USERNAME}/todo-app:latest
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MONGO_URI: ${MONGO_URI}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
    ports:
      - "80:80"
